server:
  port: 7070
spring:
  servlet:
    #配置最大上传文件大小，防止用户恶意上传大数据来浪费甚至击溃服务器
    multipart:
      #配置上传的文件最大为10mb，超过则会拒绝
      max-file-size: 10MB
      #设置整个http请求，包括所有文件和表单数据的最大大小为15mb
      max-request-size: 15MB
  application:
    name: easylive-web
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bilibili?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 1998229wang
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #设置连接池的名字，方便以后调用
      pool-name: HikariCPDatasource
      #设置连接池最大空闲数量
      minimum-idle: 5
      #设置空闲线程的最大空闲时间，如果超过这个时间则会被关闭并清除
      idle-timeout: 180000
      #配置连接池最大连接数
      maximum-pool-size: 10
      #设置提交模式，如果为false，则需要手动提交和回滚
      auto-commit: true
      #设置连接的最大生命周期，任何连接不管出于什么状态，一旦超过了这个时间，都会被关闭并重新创建
      max-lifetime: 1800000
      #设置获取连接的超时时间，如果超过这个时间会抛出异常
      connection-timeout: 30000
      #设置用来测试连接的sql语句为SELECT 1，连接池会使用这个sql语句来测试与数据库的连接
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 192.168.88.130
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000
    password: 111
#mybatis 大小写转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true

project:
  folder: d:/webser/bilibili-project/
log:
  root:
    level: debug